name: Sync Docs 
on:
  push:
    paths:
      - '**.asciidoc'
      - '**.md'    
      - '**.adoc'
    branches:
      - master
  workflow_dispatch:
jobs:
  docsync:
    uses: devonfw/.github/.github/workflows/devonfw-sync-docs.yml@master
    secrets:
      RESUSABLE_GH_ACTION_TOKEN: ${{ secrets.GHA_TOKEN }}
      RESUSABLE_BUILD_USER: ${{ secrets.BUILD_USER }}
      RESUSABLE_BUILD_USER_PASSWD: ${{ secrets.BUILD_USER_PASSWD }}
      RESUSABLE_BUILD_USER_EMAIL: ${{ secrets.BUILD_USER_EMAIL }}      
